source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/magnetsystems/Specs.git'
source 'https://github.com/magnetsystems/iOS-Distribution'

xcodeproj 'MMX Tests'
workspace '../MMX'
inhibit_all_warnings!

def import_pods
  use_frameworks!
  pod 'Kiwi', '~> 2.3'
  pod 'MMX', :path => '../'
  pod 'MagnetMax', '~> 2.4.1'
end

target :ios do
  platform :ios, '8.0'
  link_with 'iOS Tests'
  import_pods
end

# target :osx do
#   platform :osx, '10.9'
#   link_with 'OS X Tests'
#   import_pods
# end
